import Hero from "./Hero"
import PopularProducts from "./PopularProducts"
import SuperQuality from "./SuperQuality"
import Services from "./Services.jsx/"
import SpecialOffer from "./SpecialOffers"
import CustomerReviews from "./CustomerReviews"
import Subscribe from "./Subscribe"
import Footer from "./Footer"